version: 2.1

jobs:
  build:
    docker:
      - image: node:18  # Use the official Node.js image
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t vishnus1793/portfolio:latest .

      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Push Docker Image
          command: docker push vishnus1793/portfolio:latest
